FROM rocker/r-apt:bionic

USER root 

RUN apt-get update && \ 
    apt-get install -y -qq  \
		apt-utils \
		r-cran-ncmisc \
		r-cran-optparse \
		r-cran-jsonlite

# docker build -t test-base -f Dockerfile.test-base .